services:
    _defaults:
        autowire: true
        autoconfigure: true

    TomoPongrac\WebshopApiBundle\Command\SeedCategoriesCommand:
        tags:
            - { name: 'console.command' }

    TomoPongrac\WebshopApiBundle\Command\SeedTaxCategoriesCommand:
        tags:
            - { name: 'console.command' }

    TomoPongrac\WebshopApiBundle\Command\SeedProductsCommand:
        tags:
            - { name: 'console.command' }

    TomoPongrac\WebshopApiBundle\Command\SeedPriceListProductCommand:
        tags:
            - { name: 'console.command' }
