services:
    _defaults:
        autowire: true
        autoconfigure: true

    TomoPongrac\WebshopApiBundle\Command\SeedCategoriesCommand:
        tags:
            - { name: 'console.command' }

    TomoPongrac\WebshopApiBundle\Command\SeedTaxCategoriesCommand:
        tags:
            - { name: 'console.command' }

    TomoPongrac\WebshopApiBundle\Command\SeedProductsCommand:
        tags:
            - { name: 'console.command' }

    TomoPongrac\WebshopApiBundle\Command\SeedPriceListProductCommand:
        tags:
            - { name: 'console.command' }

    TomoPongrac\WebshopApiBundle\Command\SeedContractListProductCommand:
        tags:
            - { name: 'console.command' }

    TomoPongrac\WebshopApiBundle\Controller\:
        resource: '../../../src/Controller/'
        tags: ['controller.service_arguments']

    TomoPongrac\WebshopApiBundle\Serializer\CustomObjectNormalizer:
        arguments: ['@serializer.normalizer.object']
        tags: ['serializer.normalizer']

    TomoPongrac\WebshopApiBundle\Service\:
        resource: '../../../src/Service/*'
